map/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='frontpage'),
    path('znajdz-mnie/', views.SendLocationView.as_view(), name='get_location'),
    # path('miasto/', views.SendTownView.as_view(), name='get_town'),
    path('w-okolicy/', views.NearbyView.as_view(), name='nearby'),
    path('znajdz-sklep/', views.GetPointView.as_view(), name='get_point'),
    path('sklepy/', views.ShowShopsView.as_view(), name='shops'),
    # path('w-miescie/', views.TownView.as_view(), name='town'),
    # path('autocomplete/', views.AutocompleteView.as_view(), name='autocomplete'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from map import views as map_views
from user.views import UserViewSet

from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'Shops', map_views.ShopViewSet)
# router.register(r'Towns', map_views.TownViewSet)
router.register(r'Users', UserViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('admin/', admin.site.urls),
    path('', include('map.urls')),
    path('', include('user.urls')),
    path('', include('management.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

map/models.py
from django.conf import settings
from django.contrib.gis.db.models import PointField
from django.db import models
from django.contrib.auth.models import User

from rest_framework import serializers


class Shop(models.Model):
    name = models.CharField(verbose_name='nazwa', max_length=100)
    # town = models.ForeignKey('Town', verbose_name='miasto', on_delete=models.CASCADE, related_name='shops')
    # address = models.CharField(verbose_name='adres', max_length=100)
    opening_hour = models.TimeField(verbose_name='otwarcie')
    closing_hour = models.TimeField(verbose_name='zamkniecie')
    photo = models.ImageField(verbose_name='zdjecie', upload_to='photos', blank=True)
    geo_point = PointField(verbose_name='polozenie')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='właściciel', related_name='shops')
    created = models.DateTimeField(auto_now_add=True, verbose_name='data dodania')
    modified = models.DateTimeField(auto_now=True, verbose_name='data modyfikacji')

    def __str__(self):
        return self.name

# class Town(models.Model):
#     town = models.CharField(verbose_name='miasto', max_length=50, unique=True)
#
#     def __str__(self):
#         return self.town

class Sundays(models.Model):
    date = models.DateField(verbose_name='Data', unique=True)
    tradable = models.BooleanField(verbose_name='Jest otwarty?', default='false')

    def __str__(self):
        return str(self.date)


# class TownSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = Town
#         fields = ('town',)
#
# class CreatableSlugRelatedField(serializers.SlugRelatedField):
#
#     def to_internal_value(self, data):
#         try:
#             return self.get_queryset().get_or_create(**{self.slug_field: data})[0]
#         except ObjectDoesNotExist:
#             self.fail('does_not_exist', slug_name=self.slug_field, value=smart_text(data))
#         except (TypeError, ValueError):
#             self.fail('invalid')

class ShopSerializer(serializers.HyperlinkedModelSerializer):

    # town = CreatableSlugRelatedField(slug_field='town', queryset=Town.objects.all())
    ## town_send = serializers.CharField(max_length=50, write_only='True')

    class Meta:
        model = Shop
        # fields = ('name', 'address', 'opening_hour', 'closing_hour', 'owner', 'geo_point', 'town', 'url')
        read_only_fields = ('owner',)
        fields = ('name', 'opening_hour', 'closing_hour', 'owner', 'geo_point', 'url')



    def create(self, validated_data):
        request = self.context['request']
        owner = request.user
        # town = validated_data.pop('town')
        # town, exist = Town.objects.get_or_create(town=town)
        # shop = Shop.objects.create(owner=owner, town=town, **validated_data)
        return shop

    def update(self, instance, validated_data):
        instance.geo_point = validated_data.get('geo_point', instance.geo_point)
        instance.name = validated_data.get('name', instance.name)
        # instance.address = validated_data.get('address', instance.address)
        # if(validated_data.get('town')):
        #     town = validated_data.pop('town')
        #     town, exist = Town.objects.get_or_create(town=town)
        # instance.town = town
        # town = validated_data.get('town', instance.town)
        instance.opening_hour = validated_data.get('opening_hour', instance.opening_hour)
        instance.closing_hour = validated_data.get('closing_hour', instance.closing_hour)
        instance.save()
        return instance

class SundaysSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Sundays
        fields = ('date', 'tradable')

map/forms.py
from django.contrib.gis.forms import PointField
from django.core.validators import MinValueValidator, MaxValueValidator
from django import forms
from django.forms import HiddenInput
from mapwidgets import GooglePointFieldWidget

# from map.models import Town


class SendLocationForm(forms.Form):
    location = PointField(widget=HiddenInput(), error_messages={'invalid':'Podana lokacja jest nieprawidłowa'})
    distance = forms.IntegerField(validators=[MaxValueValidator(100000), MinValueValidator(500)], error_messages={
        'invalid':'Nieprawidłowy dystans', 'required':'Nie podałeś punktu'
    })

# class SendTownForm(forms.Form):
#     model = Town
#     town = forms.CharField(error_messages={'invalid':'Wpisz prawidłową nazwę miasta',
#                            'required':'Nie podałeś nazwy miasta'})

class MapForm(forms.Form):
    class Meta:
        widgets = {
            'geo_point': GooglePointFieldWidget,
        }
        error_messages = {
            'geo_point': {
                'invalid': 'Nieprawidłowy punkt na mapie',
                'required': 'Nie wybrałeś żadnego punktu na mapie',
            }
        }

    geo_point = PointField()
    distance = forms.IntegerField(validators=[MaxValueValidator(100000), MinValueValidator(500)], error_messages={
        'invalid': 'Nieprawidłowy dystans', 'required': 'Nie podałeś punktu'
    })

map/views.py
from datetime import datetime

from django.conf import settings
from django.contrib import messages
from django.contrib.gis.db.models.functions import Distance
from django.contrib.gis.geos import GEOSGeometry
from django.contrib.gis.measure import D
from django.db.models import Q, F
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, FormView
from rest_framework import viewsets
# from rest_framework.generics import ListAPIView
from rest_framework.permissions import IsAuthenticatedOrReadOnly


# from common.permissions import IsAdminOrReadOnly
# from map.forms import SendTownForm
# from map.models import ShopSerializer, TownSerializer, Sundays
# from .models import Shop, Town
from .forms import MapForm
from map.models import ShopSerializer, Sundays
from .models import Shop
from .forms import SendLocationForm

from common.mixins import AjaxTemplateMixin, AjaxableSelfRedirectOnPostMixIn

google_key = settings.GOOGLE_API_KEY

class IndexView(AjaxTemplateMixin, ListView):
    template_name = 'index.html'
    paginate_by = 8
    model = Sundays
    queryset = Sundays.objects.all().filter(date__gte=datetime.now()).order_by('date')

class SendLocationView(AjaxableSelfRedirectOnPostMixIn, AjaxTemplateMixin, FormView):
    template_name = 'map/get_location.html'
    form_class = SendLocationForm

class NearbyView(AjaxTemplateMixin, ListView):
    template_name = 'map/nearby.html'
    model = Shop
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        if(not self.request.GET.get('location') or not self.request.GET.get('distance')):
            if self.request.is_ajax():
                return JsonResponse({'redirect':reverse('get_location')})
            return redirect(reverse('get_location'))
        sup = super().get(request, *args, **kwargs)
        return sup

    def get_queryset(self):
        request=self.request
        qs = super().get_queryset()
        location = request.GET.get('location')
        max_distance = request.GET.get('distance')
        if(request.GET.get('opened')):
            currentTime = datetime.now().time()
            qs =  qs.filter(Q(opening_hour__lte=F('closing_hour')) &
                            Q(opening_hour__lte=currentTime) &
                            Q(closing_hour__gte=currentTime)) | qs.filter(Q(opening_hour__gt=F('closing_hour')) &
                       Q(opening_hour__lt=currentTime) &
                       Q(closing_hour__lt=currentTime)) | qs.filter(Q(opening_hour__gt=F('closing_hour')) &
                                                                     Q(opening_hour__gt=currentTime) &
                                                                     Q(closing_hour__gt=currentTime))
        if(location):
            point = GEOSGeometry(location)
            qs = qs.filter(geo_point__distance_lte=(point, D(m=max_distance))).\
                annotate(distance=Distance('geo_point', point)).order_by('distance')
        if not qs:
            messages.error(request, 'brak sklepów obok ciebie')
        return qs

    def get_context_data(self):
        request = self.request
        max_distance = int(request.GET.get('distance'))
        context = super().get_context_data()
        if (request.GET.get('opened')):
            currentTime = datetime.now().time()
            context['time'] = currentTime
        context['unit'] = 'm'
        if max_distance>=1000:
            max_distance/=1000
            context['unit'] = 'km'
        context['distance'] = max_distance
        return context

# class SendTownView(AjaxableSelfRedirectOnPostMixIn, AjaxTemplateMixin, FormView):
#     template_name = 'map/get_town.html'
#     form_class = SendTownForm
#
#
# class TownView(AjaxTemplateMixin, ListView):
#     template_name = 'map/town.html'
#     model = Shop
#
#     def get(self, request, *args, **kwargs):
#         if(not self.request.GET.get('town')):
#             if self.request.is_ajax():
#                 return JsonResponse({'redirect':reverse('get_town')})
#             return redirect(reverse('get_town'))
#         sup = super().get(request, *args, **kwargs)
#         return sup
#
#     def get_queryset(self):
#         request=self.request
#         qs = super().get_queryset()
#         if(request.GET.get('opened')):
#             currentTime = datetime.now().time()
#             qs =  qs.filter(Q(opening_hour__lte=F('closing_hour')) &
#                             Q(opening_hour__lte=currentTime) &
#                             Q(closing_hour__gte=currentTime)) | qs.filter(Q(opening_hour__gt=F('closing_hour')) &
#                        Q(opening_hour__lt=currentTime) &
#                        Q(closing_hour__lt=currentTime)) | qs.filter(Q(opening_hour__gt=F('closing_hour')) &
#                                                                      Q(opening_hour__gt=currentTime) &
#                                                                      Q(closing_hour__gt=currentTime))
#         city = request.GET.get('town')
#         if(city):
#             qs = qs.filter(town__town=city)
#         qs.order_by('name')
#         if not qs:
#             messages.error(request, 'Brak sklepów w danym mieście')
#         return qs
#
#     def get_context_data(self, **kwargs):
#         request = self.request
#         city = request.GET.get('town')
#         context = super().get_context_data()
#         if(city):
#             context['town']=city
#         return context

class GetPointView(AjaxableSelfRedirectOnPostMixIn, AjaxTemplateMixin, FormView):
    form_class = MapForm
    template_name = 'map/get_point.html'

class ShowShopsView(AjaxTemplateMixin, ListView):
    template_name = 'map/shops.html'
    model = Shop
    paginate_by = 100

    def get(self, request, *args, **kwargs):
        if(not self.request.GET.get('geo_point') or not self.request.GET.get('distance')):
            if self.request.is_ajax():
                return JsonResponse({'redirect':reverse('get_location')})
            return redirect(reverse('get_location'))
        sup = super().get(request, *args, **kwargs)
        return sup

    def get_queryset(self):
        request=self.request
        qs = super().get_queryset()
        geo_point = request.GET.get('geo_point')
        max_distance = request.GET.get('distance')
        if(request.GET.get('opened')):
            currentTime = datetime.now().time()
            qs =  qs.filter(Q(opening_hour__lte=F('closing_hour')) &
                            Q(opening_hour__lte=currentTime) &
                            Q(closing_hour__gte=currentTime)) | qs.filter(Q(opening_hour__gt=F('closing_hour')) &
                       Q(opening_hour__lt=currentTime) &
                       Q(closing_hour__lt=currentTime)) | qs.filter(Q(opening_hour__gt=F('closing_hour')) &
                                                                     Q(opening_hour__gt=currentTime) &
                                                                     Q(closing_hour__gt=currentTime))
        if(geo_point):
            point = GEOSGeometry(geo_point)
            qs = qs.filter(geo_point__distance_lte=(point, D(m=max_distance))).\
                annotate(distance=Distance('geo_point', point)).order_by('distance')
        if not qs:
            messages.error(request, 'brak sklepów obok ciebie')
        return qs

    def get_context_data(self):
        request = self.request
        point = request.GET.get('geo_point')
        max_distance = int(request.GET.get('distance'))
        context = super().get_context_data()
        if (request.GET.get('opened')):
            currentTime = datetime.now().time()
            context['time'] = currentTime
        context['distance'] = max_distance
        context['geo_point'] = point
        if max_distance<=100:
            context['zoom'] = 15
            context['unit'] = 'm'
        if max_distance<=250:
            context['zoom'] = 14
            context['unit'] = 'm'
        if max_distance<=500:
            context['zoom'] = 13
            context['unit'] = 'm'
        if max_distance<=999:
            context['zoom'] = 12
            context['unit'] = 'm'
            return context
        if max_distance<=2500:
            context['zoom'] = 11
            context['unit'] = 'km'
            return context
        if max_distance<=5000:
            context['zoom'] = 10
            context['unit'] = 'km'
            return context
        if max_distance<=10000:
            context['zoom'] = 9
            context['unit'] = 'km'
            return context
        if max_distance<=25000:
            context['zoom'] = 8
            context['unit'] = 'km'
            return context
        if max_distance<=50000:
            context['zoom'] = 7
            context['unit'] = 'km'
            return context
        if max_distance<=100000:
            context['zoom'] = 6
            context['unit'] = 'km'
            return context

class ShopViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows shops to be viewed, created or edited.
    """
    queryset = Shop.objects.all().order_by('-created')
    serializer_class = ShopSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]

# class TownViewSet(viewsets.ModelViewSet):
#     """
#     Api endpoint that allows towns to be viewed, created or edited.
#     """
#     queryset = Town.objects.all()
#     serializer_class = TownSerializer
#     permission_classes = [IsAdminOrReadOnly]

# class AutocompleteView(ListAPIView):
#     serializer_class = TownSerializer
#     def get_queryset(self):
#         qs = Town.objects.all()
#         if (self.request.GET.get('town')):
#             qs = qs.filter(town__contains=self.request.GET.get('town'))
#         return qs

templates/map/get_location.html
{% extends base %}
{% block main %}
      <ul class="messages">
  {% if messages %}
    {% for message in messages %}
      <li class="alert alert-{{ message.tags }}">{{ message }}</li>
    {% endfor %}{% endif %}
  </ul>
    <div class="text-center" id="LocationSendShop">
      <h2 class="text-center"></h2>
        <h1>Wybierz odległość</h1>
        <div class="btn-group btn-group-sm margin" role="group">
        <button id="500" class="btn btn-primary">500m</button>
        <button id="1000" class="btn btn-primary">1km</button>
        <button id="5000" class="btn btn-primary">5km</button>
        <button id="20000" class="btn btn-primary">20km</button>
        <button id="50000" class="btn btn-primary">50km</button>
        <button id="100000" class="btn btn-primary">100km</button>
        </div>
        <form id="LocationSendForm" method="get" action="{% url 'nearby' %}" role="form">
        <input id="id_location" name="location" type="hidden">
          <input id="id_distance" name="distance" type="hidden">
            <label>
                <div class="btn btn-primary">
                    <input type="checkbox" id="id_opened" name="opened">
                    Otwarty w tej chwili
                </div>
            </label>
      </form>
        <button id="find_me" class="btn btn-primary btn-lg btn-block margin" onclick="getLocation()">
            Znajdź sklepy obok mnie<span class="glyphicon glyphicon-screenshot"></span>
        </button>
        <div id="geo"></div>
    </div>
{% endblock %}
{% block js %}
    <script>
        $("#find_me").hide();
        function getLocation() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(sendPosition, errorCallBack);
            }
        }

        function sendPosition(position) {
            x = position.coords.longitude;
            y = position.coords.latitude;
            lnglat = "POINT("+x+" "+y+")";
            $("#id_location").val(lnglat);
            var frm = $("#LocationSendForm");
            $.ajax({
                type: frm.attr('method'),
                url: frm.attr('action'),
                data: frm.serialize(),
                dataType: "html",
                success: function (data) {
                    $('#content').html(data);
                }
            });
        }
        function errorCallBack(error) {
            console.log("jak narazie wszystko gra");
            (error.code == error.PERMISSION_DENIED)
            {
                console.log("sanity test");
                $("#geo").html("<h1>Nie jesteśmy w stanie określić twojego położenia</h1>");
            }
        }
        $('.btn-group').on('click', '.btn', function() {
            var value=$(this).attr("id");
            $("#id_distance").val(value);
            $(this).addClass('active').siblings().removeClass('active');
            $('#find_me').show();
        });
</script>
{% endblock %}

templates/map/get_point.html
{% extends base %}
{% block main %}
    <style>
.custom-file-input ~ .custom-file-label::after {
    content: "znajdź plik";
}
    </style>
    {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li class="alert alert-{{ message.tags }}">{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}
    <div class="text-center" id="GetPoint">
        <link href="/static/mapwidgets/css/map_widgets.css" type="text/css" media="all" rel="stylesheet">
        <script type="text/javascript" src="/static/mapwidgets/js/jquery_class.js"></script>
        <script type="text/javascript" src="/static/mapwidgets/js/django_mw_base.js"></script>
        <script type="text/javascript" src="/static/mapwidgets/js/mw_google_point_field.js"></script>
        <h1>Znajdź sklep</h1>
        <hr width="80%">
          <h2 class="text-center"></h2>
        <h1>Wybierz odległość</h1>
        <div class="btn-group btn-group-sm margin" role="group">
        <button id="100" class="btn btn-primary">100m</button>
        <button id="500" class="btn btn-primary">500m</button>
        <button id="1000" class="btn btn-primary">1km</button>
        <button id="2500" class="btn btn-primary">2,5km</button>
        <button id="5000" class="btn btn-primary">5km</button>
        <button id="1000" class="btn btn-primary">10km</button>
        <button id="25000" class="btn btn-primary">25km</button>
        <button id="50000" class="btn btn-primary">50km</button>
        <button id="100000" class="btn btn-primary">100km</button>
        </div>
        <form id="GetPointForm" method="get" action="{% url 'shops' %}" role="form">
          <input id="id_distance" name="distance" type="hidden">
            <label>
                <div class="btn btn-primary">
                    <input type="checkbox" id="id_opened" name="opened">
                    Otwarty w tej chwili
                </div>
            </label>
            <div class="mw-wrap text-white" id="geo_point-mw-wrap">
                {% block container %}
                    <div class="mw-header">
                        {% block header %}
                            <div class="mw-coordinates-wrap">
                                <a  class="mw-btn mw-btn-primary mw-btn-coordinates">Koordynaty
                                    <i class="icon-down-dir" ></i></a>
                                <div class="mw-coordinates-overlay hide">
                                    <label for="geo_point-mw-overlay-latitude">
                                        Y
                                        <input type="text" id="geo_point-mw-overlay-latitude"
                                               class="form-control mw-overlay-input mw-overlay-latitude"
                                               placeholder="przykład: 41.015137'"/>
                                    </label>
                                    <label for="geo_point-mw-overlay-longitude">
                                        X
                                        <input type="text" id="geo_point-mw-overlay-longitude"
                                               class="form-control mw-overlay-input mw-overlay-longitude"
                                               placeholder="przykład: 28.979530"/>
                                    </label>
                                    <a class="mw-btn mw-btn-success mw-btn-coordinates-done pull-right">"Done"</a>
                                </div>
                            </div>

                            <a class="mw-btn mw-btn-info mw-btn-my-location" >Znajdź mnie </a>
                            <a class="mw-btn mw-btn-warning mw-btn-add-marker" ><i class="icon-location"></i>
                                Oznacz miejce</a>
                            <div class="mw-adress-input-wrap pull-right">
                                <input type="text" class="form-control pull-right"
                                       id="geo_point-mw-google-address-input"
                                       placeholder="Wpisz i wybierz adres"/>
                            </div>
                        {% endblock header %}
                    </div>

                    <div class="mw-map-wrapper">
                        <div class="mw-loader-overlay hide" >
                            <div class="mw-loader"></div>
                        </div>
                        <div id="geo_point-map-elem" class="mw-map"></div>
                        <div style="display: none" class="hide">
                            <textarea id="id_geo_point" name="geo_point">{{ serialized }}</textarea>
                            {% block extra_input %}
                            {% endblock extra_input %}
                        </div>
                    </div>
                    <div class="animated-loader"></div>
                {% endblock container %}
            </div>
            <input class="btn btn-primary" type="submit" value="Wyślij!">
        </form>
    </div>
    {% endblock %}
    {% block js %}
    <script type="application/javascript">
        function init(){
            var mapOptions = JSON.parse("{\u0022mapCenterLocationName\u0022: \u0022Polska\u0022, " +
                "\u0022mapCenterLocation\u0022: [40.2044358, \u002D101.9953523], \u0022zoom\u0022: 18, " +
                "\u0022GooglePlaceAutocompleteOptions\u0022: {\u0022componentRestrictions\u0022: " +
                "{\u0022country\u0022: \u0022pl\u0022}}, \u0022markerFitZoom\u0022: 18, \u0022" +
                "language\u0022: \u0022pl\u0022}");
            var field_value = JSON.parse("{}");

            var wrapElemSelector = "#geo_point-mw-wrap";
            var mapElemID = "geo_point-map-elem";
            var googleAutoInputID = "geo_point-mw-google-address-input";
            var locationInputID = "#id_geo_point";

            var mapWidgetOptions = {
                locationInput: $(locationInputID),
                wrapElemSelector: wrapElemSelector,
                locationFieldValue: field_value,
                mapElement: document.getElementById(mapElemID),
                mapCenterLocationName: mapOptions.mapCenterLocationName,
                mapCenterLocation: mapOptions.mapCenterLocation,
                coordinatesOverlayToggleBtn: $(".mw-btn-coordinates", wrapElemSelector),
                coordinatesOverlayDoneBtn: $(".mw-btn-coordinates-done", wrapElemSelector),
                coordinatesOverlayInputs: $(".mw-overlay-input", wrapElemSelector),
                coordinatesOverlay: $(".mw-coordinates-overlay", wrapElemSelector),
                myLocationBtn: $(".mw-btn-my-location", wrapElemSelector),
                addressAutoCompleteInput: document.getElementById(googleAutoInputID),
                deleteBtn: $(".mw-btn-delete", wrapElemSelector),
                addMarkerBtn: $(".mw-btn-add-marker", wrapElemSelector),
                loaderOverlayElem: $(".mw-loader-overlay", wrapElemSelector),
                zoom: mapOptions.zoom,
                markerFitZoom: mapOptions.markerFitZoom,
                GooglePlaceAutocompleteOptions: mapOptions.GooglePlaceAutocompleteOptions,
                markerCreateTriggerNameSpace: "google_point_map_widget:marker_create",
                markerChangeTriggerNameSpace: "google_point_map_widget:marker_change",
                markerDeleteTriggerNameSpace: "google_point_map_widget:marker_delete",
                placeChangedTriggerNameSpace: "google_point_map_widget:place_changed"
            };
            new DjangoGooglePointFieldWidget(mapWidgetOptions);
        }
        $(document).ready(function () {
           init();
        });
        $('#MapAddForm').submit(function(ev){
            var frm = $(this);
            console.log(frm);
            var data = new FormData($(this)[0]);
            ev.preventDefault();
            $.ajax({
                type: frm.attr('method'),
                url: frm.attr('action'),
                data: frm.serialize(),
                dataType: "html",
                success: function (data) {
                    $('#content').html(data);
                }
            });
        });
  $('.custom-file-input').on('change',function(){
  var fileName = $(this).val().split("\\").pop();
  $(this).next('.custom-file-label').html(fileName);
});
    </script>
    </form>
    <script>
        $('.btn-group').on('click', '.btn', function() {
            var value=$(this).attr("id");
            $("#id_distance").val(value);
        });
</script>
{% endblock %}

templates/map/get_town.html
{% extends base %}
{% block main %}
      <ul class="messages">
  {% if messages %}
    {% for message in messages %}
      <li class="alert alert-{{ message.tags }}">{{ message }}</li>
    {% endfor %}{% endif %}
  </ul>
    <div class="text-center" id="TownSendShop">
      <h2 class="text-center">Znajdź sklepy w mieście:</h2>
      <form id="TownSendForm" method="get" action="{% url 'town' %}" role="form">
          <label for="id_town">Miasto:</label>
          <input id="id_town" name="town" class="form-control" placeholder="Wpisz nazwę miasta."><br>
          <input value="Wyślij" type="submit" class="btn btn-primary" id="sender">
      </form>
        <div id="geo"></div>
    </div>
{% endblock %}
{% block js %}
    <script>
    var url="{% url 'autocomplete' %}";
    console.log(url);
    $('#id_town').autocomplete({
        source: function ( request, response ) {
            $.ajax({
                type: 'GET',
                url: url + "?town=" + $('#id_town').val(),
                dataType: "json",
                success: function(data){
                    response( $.map( data, function( value, key ) {
                        console.log(key);
                        return {
                            label: value.town,
                            value: value.town,
                        }
                    }));
                }
            });
        },
        minLength: 2,
        delay: 100
    });
    function getTown() {
            var frm = $("#TownSendForm");
            $.ajax({
                type: frm.attr('method'),
                url: frm.attr('action'),
                data: frm.serialize(),
                dataType: "html",
                success: function (data) {
                    $('#content').html(data);
                }
            });
        }

    $("form").submit(function(event){
        getTown();
        event.preventDefault();
    });
</script>
{% endblock %}