management/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('moje-sklepy/', views.MyShopsView.as_view(), name='my_shops'),
    path('dodaj-sklep/', views.AddUsingGoogleMapsView.as_view(), name='map_based'),
#    path('google/reverse_geocoding/', views.ReverseGeocodingView.as_view(), name='reverse_geocoding'),
]

map/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='frontpage'),
    path('znajdz-mnie/', views.SendLocationView.as_view(), name='get_location'),
    # path('miasto/', views.SendTownView.as_view(), name='get_town'),
    path('w-okolicy/', views.NearbyView.as_view(), name='nearby'),
    path('znajdz-sklep/', views.GetPointView.as_view(), name='get_point'),
    path('sklepy/', views.ShowShopsView.as_view(), name='shops'),
    # path('w-miescie/', views.TownView.as_view(), name='town'),
    # path('autocomplete/', views.AutocompleteView.as_view(), name='autocomplete'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from map import views as map_views
from user.views import UserViewSet

from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'Shops', map_views.ShopViewSet)
# router.register(r'Towns', map_views.TownViewSet)
router.register(r'Users', UserViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('admin/', admin.site.urls),
    path('', include('map.urls')),
    path('', include('user.urls')),
    path('', include('management.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

management/forms.py
from django import forms
from django.core.exceptions import ValidationError

from map.models import Shop

from mapwidgets.widgets import GooglePointFieldWidget
from captcha.fields import ReCaptchaField


class ShopForm(forms.ModelForm):
    class Meta:
        model = Shop
        # fields = ['opening_hour', 'closing_hour', 'name', 'geo_point', 'address', 'photo']
        fields = ['opening_hour', 'closing_hour', 'name', 'geo_point', 'photo']
        widgets = {
            'geo_point': GooglePointFieldWidget,
        }
        error_messages = {
            'geo_point':{
                'invalid' : 'Nieprawidłowy punkt na mapie',
                'required' : 'Nie wybrałeś żadnego punktu na mapie',
            },
            'address':{
                'required' : 'Nie byliśmy w stanie utworzyć adresu',
                'invalid' : 'Nastąpił niespodziewany błąd(RRoD, Error E01)',
            }
        }

    name = forms.CharField(label='Nazwa sklepu', error_messages={'required': 'Pole "Nazwa sklepu" jest wymagane'})

    opening_hour = forms.TimeField(label='Godzina otwarcia sklepu',
                                   error_messages={'invalid':'Wprowadź poprawną godzinę otwarcia sklepu',
                                                   'required': 'Pole "Godzina otwarcia sklepu" jest wymagane'},
                                   input_formats=['%H:%M'],
                                   widget=forms.TimeInput(format='%H:%M'))

    closing_hour = forms.TimeField(label='Godzina zamknięcia sklepu',
                                   error_messages={'invalid':'Wprowadź poprawną godzinę zamknięcia sklepu',
                                                   'required': 'Pole "Godzina zamknięcia sklepu" jest wymagane'},
                                   input_formats=['%H:%M'],
                                   widget=forms.TimeInput(format='%H:%M'))
    photo = forms.ImageField(label='Wybierz zdjęcie sklepu',
                               help_text='Zdjęcie powinno ukazywać wejście sklepu.', required=False)

    def clean_photo(self):
        image = self.cleaned_data.get('photo', False)
        if image:
            if image.size > 4 * 1024 * 1024:
                raise ValidationError("Zdjęcie jest zbyt duże(max. 4MB)")
            return image
        else:
            raise ValidationError("Nie byliśmy w stanie przetworzyć zdjęcia")

class ShopCaptchaForm(ShopForm):
    captcha = ReCaptchaField(attrs={'size': 'normal', 'theme' : 'clean', },
                             error_messages={'required': "Nie uzupełniłeś captcha"})

management/views.py
# import requests
# from django.http import JsonResponse
from django.urls import reverse
from django.views.generic import TemplateView, FormView, CreateView, ListView
from django.conf import settings
# from django.views.generic.base import View

from . import forms

from common.mixins import LoginRequiredAjaxMixIn, AjaxTemplateMixin, AjaxableResponseMixin
# from map.models import Shop, Town
from map.models import Shop

google_key = settings.GOOGLE_API_KEY


class MyShopsView(LoginRequiredAjaxMixIn, AjaxTemplateMixin, ListView):
    template_name = 'management/my_shops.html'
    model = Shop
    def get_queryset(self):
        qs = Shop.objects.all().filter(owner=self.request.user)
        return qs

class Addshop(LoginRequiredAjaxMixIn ,AjaxTemplateMixin, TemplateView):
    template_name = 'management/addshop.html'

class AddFromCurrentLocationView(AjaxableResponseMixin, LoginRequiredAjaxMixIn, AjaxTemplateMixin, FormView):
    form_class = forms.ShopCaptchaForm
    template_name = 'management/lokacja.html'


class AddUsingGoogleMapsView(AjaxableResponseMixin, LoginRequiredAjaxMixIn, AjaxTemplateMixin, CreateView):
    model = Shop
    message = "Twój sklep został utworzony."
    form_class = forms.ShopCaptchaForm
    template_name = 'management/mapa.html'
    def get_success_url(self):
        return reverse('my_shops')

    def form_valid(self, form):
        # long_adres = form.cleaned_data.get('address')
        # list = long_adres.split(', ')
        #list[-1] is the country, we don't need it
        #list[-2] is the town, we put it into town field
        # form_town = ''.join(list[-2])
        # address = ' '.join(list[:len(list)-2])
        # try:
        #     town_object = Town.objects.get(town=form_town)
        # except Town.DoesNotExist:
        #     town_object = None
        # if(town_object):
        #     form.instance.town = town_object
        # else:
        #     town_object = Town.objects.create(town=form_town)
        #     form.instance.town = town_object
        # form.instance.address = address
        form.instance.owner = self.request.user
        return super().form_valid(form)

# class ReverseGeocodingView(LoginRequiredAjaxMixIn, View):
#     part1 = "https://maps.googleapis.com/maps/api/geocode/json?latlng="
#     part2 = "&language=pl&key="
#     def get(self, request, *args, **kwargs):
#         data = {'error':'Nieprawidłowy sposób użycia'}
#         return JsonResponse(data, status=400)
#
#     def post(self, request, *args, **kwargs):
#         latlng = request.POST['latlng']
#         url = self.part1+latlng+self.part2+google_key
#         serialized_data = requests.get(url).json()
#         full_name = serialized_data['results'][00]['formatted_address']
#         list = full_name.split(',')
#         return JsonResponse({"town":list[-2], 'adres':list[:len(list)-2]})

templates/management/addshop.html
{% extends base %}
{% block main %}
  <ul class="messages">
  {% if messages %}
    {% for message in messages %}
      <li class="alert alert-{{ message.tags }}">{{ message }}</li>
    {% endfor %}{% endif %}
  </ul>
    <h1 class="text-center">Wybierz jak chcesz dodać sklep</h1>
    <div class="text-center">
    <a id="lokacja" href="{% url "location_based" %}"><button class="btn btn-primary btn-lg">
        bazując na moim aktualnym położeniu</button></a>
    <a id="mapa" href="{% url 'map_based' %}"><button class="btn btn-primary btn-lg">
        korzystając z mapy google</button></a>
    </div>
    <div id="box">{% block box %}{% endblock %}</div>
    <div id="geo" class="text-center"></div>
{% endblock %}
{% block js %}
    <script>
    $("#lokacja").click(function(event){
        event.preventDefault();
        $("#box").load("{% url 'location_based' %}");
    });
    $("#mapa").click(function(event){
        event.preventDefault();
        $("#box").load("{% url 'map_based' %}");
    });
    </script>
{% endblock %}

templates/management/lokacja.html
{% extends base %}
{% block main %}
    {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li class="alert alert-{{ message.tags }}">{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}
        {% if not request.is_ajax %}
        <h1 class="text-center">Wybierz jak chcesz dodać sklep</h1>
    <div class="text-center">
    <a id="lokacja" href="{% url "location_based" %}"><button class="btn btn-primary btn-lg">
        bazując na moim aktualnym położeniu</button></a>
    <a id="mapa" href="{% url 'map_based' %}"><button class="btn btn-primary btn-lg">
        korzystając z mapy google</button></a>
    </div>
    {% endif %}
    <div class="text-center" id="LocationAddShop">
    <hr width="80%">
            <div class ='AddShop'>
      <h2 class="text-center">Uzupełnij informacje o sklepie</h2>
      <form id="ShopAddForm" method="post" action="{% url 'location_based' %}" role="form">
        {% csrf_token %}
        <div class="form-group{% if form.name.errors %} has-error{% endif %}">
          <label for="name">Nazwa sklepu</label>
          <input type="text" class="form-control" id="id_name" name="name">
          {% for error in form.username.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
        <div class="form-group{% if form.opening_hour.errors %} has-error{% endif %}">
          <label for="opening_hour">Godzina otwarcia sklepu</label>
          <input class="form-control" id="id_opening_hour" name="opening_hour">
          {% for error in form.password.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
              <div class="form-group{% if form.closing_hour.errors %} has-error{% endif %}">
          <label for="opening_hour">Godzina zamknięcia sklepu</label>
          <input class="form-control" id="id_closing_hour" name="closing_hour">
          {% for error in form.password.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
        <div class="form-group text-center">
          <input value="Dodaj sklep" type="submit" class="btn btn-primary btn-lg">
        </div>
      </form>
    </div>
{% endblock %}
{% block js %}
    <script>
    $(".AddShop").hide();
        function getLocation() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(sendPosition, errorCallBack);
            }
        }

        function sendPosition(position) {
            x = position.coords.longitude;
            y = position.coords.latitude;
            latlng = y+","+x;
            $(".AddShop").show();
            $.post("{% url 'reverse_geocoding' %}", {"latlng": latlng, csrfmiddlewaretoken: '{{ csrf_token }}'},
                function (data){
                $("#geo").html('<hr width="80%"><h1 class="text-center">Twój adres:' +
                    '</h1>Miasto:'+data.town+' Adres: '+data.adres);
                });

        }
        function errorCallBack(error) {
            (error.code == error.PERMISSION_DENIED)
            {
                console.log("sanity test");
                $("#geo").html("<h1>Nie jesteśmy w stanie określić twojego położenia</h1>");
            }
        }
        getLocation();
    //handling form submit
    formsubmit('#ShopAddForm',
        function(data){
            if (data.ok){
                $("#user_nav").load("{% url 'user_nav' %}");
                $("#content").load("{% url 'frontpage' %}");
                $(".messages").append(addmessage(data.message));
            }
        },
        function (data) {
            if(data.responseJSON) {
                console.log(data.responseJSON.values);
                for(var i in data.responseJSON)
                {
                    $(".messages").append(addmessage(data.responseJSON[i], 'danger'));
                }
            }
            $("#geo").load("{% url 'location_based' %}");
        });
</script>
{% endblock %}

templates/management/mapa.html
{% extends base %}
{% block main %}
    <style>
.custom-file-input ~ .custom-file-label::after {
    content: "znajdź plik";
}
    </style>
    {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li class="alert alert-{{ message.tags }}">{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}
    <div class="text-center" id="LocationAddShop">
        <link href="/static/mapwidgets/css/map_widgets.css" type="text/css" media="all" rel="stylesheet">
        <script type="text/javascript" src="/static/mapwidgets/js/jquery_class.js"></script>
        <script type="text/javascript" src="/static/mapwidgets/js/django_mw_base.js"></script>
        <script type="text/javascript" src="/static/mapwidgets/js/mw_google_point_field.js"></script>
    <h1>Dodaj sklep</h1>
        <hr width="80%">
        <form id="MapAddForm" method="post" action="{% url 'map_based' %}" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            <div class="form-group">
                <label for="id_opening_hour">Godzina otwarcia sklepu:</label>
                <input class="form-control" name="opening_hour" required=""
                       id="id_opening_hour" type="text" placeholder="06:00">
            </div>
            <div class="form-group">
                <label for="id_closing_hour">Godzina zamknięcia sklepu:</label>
                <input class="form-control" name="closing_hour" required=""
                       id="id_closing_hour" type="text" placeholder="12:00">
            </div>
            <div class="form-group">
                <label for="id_name">Nazwa sklepu:</label>
                <input class="form-control" name="name" required="" id="id_name" type="text">
            </div>
            <div class="form-group">
                <label>Zdjęcie sklepu(opcjonalne):</label>
                <div class="custom-file" lang="pl">
                    <input type="file" class="custom-file-input" id="id_photo" name="photo">
                    <label class="custom-file-label" for="id_photo">Wybierz zdjęcie</label>
                </div>
            </div>
            <input name="address" id="id_address" type="hidden">
            <div class="mw-wrap text-white" id="geo_point-mw-wrap">
                {% block container %}
                    <div class="mw-header">
                        {% block header %}
                            <div class="mw-coordinates-wrap">
                                <a  class="mw-btn mw-btn-primary mw-btn-coordinates">Koordynaty
                                    <i class="icon-down-dir" ></i></a>
                                <div class="mw-coordinates-overlay hide">
                                    <label for="geo_point-mw-overlay-latitude">
                                        Y
                                        <input type="text" id="geo_point-mw-overlay-latitude"
                                               class="form-control mw-overlay-input mw-overlay-latitude"
                                               placeholder="przykład: 41.015137'"/>
                                    </label>
                                    <label for="geo_point-mw-overlay-longitude">
                                        X
                                        <input type="text" id="geo_point-mw-overlay-longitude"
                                               class="form-control mw-overlay-input mw-overlay-longitude"
                                               placeholder="przykład: 28.979530"/>
                                    </label>
                                    <a class="mw-btn mw-btn-success mw-btn-coordinates-done pull-right">"Done"</a>
                                </div>
                            </div>

                            <a class="mw-btn mw-btn-info mw-btn-my-location" >Znajdź mnie </a>
                            <a class="mw-btn mw-btn-warning mw-btn-add-marker" ><i class="icon-location"></i>
                                Oznacz miejce</a>
                            <div class="mw-adress-input-wrap pull-right">
                                <input type="text" class="form-control pull-right"
                                       id="geo_point-mw-google-address-input"
                                       placeholder="Wpisz i wybierz adres"/>
                            </div>
                        {% endblock header %}
                    </div>

                    <div class="mw-map-wrapper">
                        <div class="mw-loader-overlay hide" >
                            <div class="mw-loader"></div>
                        </div>
                        <div id="geo_point-map-elem" class="mw-map"></div>
                        <div style="display: none" class="hide">
                            <textarea id="id_geo_point" name="geo_point">{{ serialized }}</textarea>
                            {% block extra_input %}
                            {% endblock extra_input %}

                        </div>
                    </div>
                    <div class="animated-loader"></div>
                {% endblock container %}
            </div>
        <div class="form-group">
            {{ form.captcha }}
        </div>
            <input class="btn btn-primary" type="submit" value="Wyślij!">

    </form>
    </div>
    <script type="application/javascript">
        function init(){
            var mapOptions = JSON.parse("{\u0022mapCenterLocationName\u0022: \u0022Polska\u0022, " +
                "\u0022mapCenterLocation\u0022: [40.2044358, \u002D101.9953523], \u0022zoom\u0022: 18, " +
                "\u0022GooglePlaceAutocompleteOptions\u0022: {\u0022componentRestrictions\u0022: " +
                "{\u0022country\u0022: \u0022pl\u0022}}, \u0022markerFitZoom\u0022: 18, \u0022" +
                "language\u0022: \u0022pl\u0022}");
            var field_value = JSON.parse("{}");

            var wrapElemSelector = "#geo_point-mw-wrap";
            var mapElemID = "geo_point-map-elem";
            var googleAutoInputID = "geo_point-mw-google-address-input";
            var locationInputID = "#id_geo_point";

            var mapWidgetOptions = {
                locationInput: $(locationInputID),
                wrapElemSelector: wrapElemSelector,
                locationFieldValue: field_value,
                mapElement: document.getElementById(mapElemID),
                mapCenterLocationName: mapOptions.mapCenterLocationName,
                mapCenterLocation: mapOptions.mapCenterLocation,
                coordinatesOverlayToggleBtn: $(".mw-btn-coordinates", wrapElemSelector),
                coordinatesOverlayDoneBtn: $(".mw-btn-coordinates-done", wrapElemSelector),
                coordinatesOverlayInputs: $(".mw-overlay-input", wrapElemSelector),
                coordinatesOverlay: $(".mw-coordinates-overlay", wrapElemSelector),
                myLocationBtn: $(".mw-btn-my-location", wrapElemSelector),
                addressAutoCompleteInput: document.getElementById(googleAutoInputID),
                deleteBtn: $(".mw-btn-delete", wrapElemSelector),
                addMarkerBtn: $(".mw-btn-add-marker", wrapElemSelector),
                loaderOverlayElem: $(".mw-loader-overlay", wrapElemSelector),
                zoom: mapOptions.zoom,
                markerFitZoom: mapOptions.markerFitZoom,
                GooglePlaceAutocompleteOptions: mapOptions.GooglePlaceAutocompleteOptions,
                markerCreateTriggerNameSpace: "google_point_map_widget:marker_create",
                markerChangeTriggerNameSpace: "google_point_map_widget:marker_change",
                markerDeleteTriggerNameSpace: "google_point_map_widget:marker_delete",
                placeChangedTriggerNameSpace: "google_point_map_widget:place_changed"
            };
            new DjangoGooglePointFieldWidget(mapWidgetOptions);
        }
        $(document).ready(function () {
           init();
        });
        $('#MapAddForm').submit(function(ev){
            adres = $("#geo_point-mw-google-address-input").val();
            $("#id_address").val(adres);
            var frm = $(this);
            console.log(frm);
            var data = new FormData($(this)[0]);
            ev.preventDefault();
            $.ajax({
                type: frm.attr('method'),
                url: frm.attr('action'),
                data: data,
                enctype: 'multipart/form-data',
                timeout: 600000,
                processData: false,  // Important!
                contentType: false,
                cache: false,
                success: function(data){
                    if (data.ok){
                        $("#content").load("{% url 'my_shops' %}");
                        $(".messages").append(addmessage(data.message));
                    }
                },
                error: function (data) {
                    if(data.responseJSON) {
                        console.log(data.responseJSON.values);
                        for(var i in data.responseJSON)
                        {
                            $(".messages").append(addmessage(data.responseJSON[i], 'danger'));
                        }
                    }
                    $("#box").load("{% url 'map_based' %}");
                }
            });
        });
  $('.custom-file-input').on('change',function(){
  var fileName = $(this).val().split("\\").pop();
  $(this).next('.custom-file-label').html(fileName);
});
    </script>
    </form>

{% endblock %}