map/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='frontpage'),
    path('znajdz-mnie/', views.SendLocationView.as_view(), name='get_location'),
    # path('miasto/', views.SendTownView.as_view(), name='get_town'),
    path('w-okolicy/', views.NearbyView.as_view(), name='nearby'),
    path('znajdz-sklep/', views.GetPointView.as_view(), name='get_point'),
    path('sklepy/', views.ShowShopsView.as_view(), name='shops'),
    # path('w-miescie/', views.TownView.as_view(), name='town'),
    # path('autocomplete/', views.AutocompleteView.as_view(), name='autocomplete'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from map import views as map_views
from user.views import UserViewSet

from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'Shops', map_views.ShopViewSet)
# router.register(r'Towns', map_views.TownViewSet)
router.register(r'Users', UserViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('admin/', admin.site.urls),
    path('', include('map.urls')),
    path('', include('user.urls')),
    path('', include('management.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('logowanie/', views.LoginView2.as_view(), name='login'),
    path('wyloguj/', views.LogoutView2.as_view(), name='logout'),
    path('rejestracja/', views.RegisterView.as_view(), name='register'),
    path('zmiana-hasla/', views.PasswordChangeView2.as_view(), name='password_change'),
    path('zmiana-hasla-ukonczona/', views.PasswordChangeDoneView2.as_view(), name='password_change_done'),
    path('user-nav/', views.UserNavView.as_view(), name='user_nav'),
    path('przypomnij-haslo/', views.PasswordResetView2.as_view(), name='password_reset'),
    path('email-z-informacjami-wyslany/', views.PasswordResetDoneView2.as_view(), name='password_reset_done'),
    path('generuj-haslo/<uidb64>/<token>/', views.PasswordResetConfirmView2.as_view(), name='password_reset_confirm'),
    path('generuj-haslo/zrobione/', views.PasswordResetCompleteView2.as_view(), name='password_reset_complete'),
    path('sprawdz/username/<username>/', views.CheckUsername.as_view(), name='check_username'),
    path('sprawdz/mail/<email>/', views.CheckMail.as_view(), name='check_mail')
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from rest_framework import serializers

from map.models import ShopSerializer


class Profile(models.Model):
    user = models.ForeignKey(User, related_name='profil', on_delete=models.CASCADE, verbose_name='profil')


class UserSerializer(serializers.HyperlinkedModelSerializer):

    class Meta:
        model = User
        fields = ('username', 'shops',)
        read_only_fields = ('shops',)

user/forms.py
#-*- coding: utf-8 -*-
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import AuthenticationForm, UsernameField, PasswordResetForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _
from captcha.fields import ReCaptchaField


class MyAuthenticationForm(AuthenticationForm):
    username = UsernameField(
        error_messages={'required': 'Pole "Nazwa użytkownika" jest wymagane', },
        max_length=254,
        widget=forms.TextInput(attrs={'autofocus': True}),
    )
    password = forms.CharField(
        error_messages={'required': 'Pole "Hasło" jest wymagane', },
        label="Password",
        strip=False,
        widget=forms.PasswordInput,
    )
    captcha = ReCaptchaField(attrs={'size': 'normal', 'theme' : 'clean', },
                             error_messages={'required': "Nie uzupełniłeś captcha"})
    error_messages = {
        'invalid_login': (
            'Nazwa użytkownika i hasło się nie zgadzają lub konto jest nieaktywne'
        ),
        'inactive': "To konto jest nieaktywne",
    }


def forbidden_usernames_validator(value):
    forbidden_usernames = ['admin', 'settings', 'news', 'about', 'help',
                           'signin', 'signup', 'signout', 'terms', 'privacy',
                           'cookie', 'new', 'login', 'logout', 'administrator',
                           'join', 'account', 'username', 'root', 'blog',
                           'user', 'users', 'billing', 'subscribe', 'reviews',
                           'review', 'blog', 'blogs', 'edit', 'mail', 'email',
                           'home', 'job', 'jobs', 'contribute', 'newsletter',
                           'shop', 'profile', 'register', 'auth',
                           'authentication', 'campaign', 'config', 'delete',
                           'remove', 'forum', 'forums', 'download',
                           'downloads', 'contact', 'blogs', 'feed', 'feeds',
                           'faq', 'intranet', 'log', 'registration', 'search',
                           'explore', 'rss', 'support', 'status', 'static',
                           'media', 'setting', 'css', 'js', 'follow',
                           'activity', 'questions', 'articles', 'network', ]

    if value.lower() in forbidden_usernames:
        raise ValidationError('Zakazana nazwa użytkownika. ')

def invalid_username_validator(value):
    if '@' in value or '+' in value or '-' in value:
        raise ValidationError('Podaj prawidłową nazwę użytkownika.')

def unique_email_validator(value):
    if User.objects.filter(email__iexact=value).exists():
        raise ValidationError('Ten email jest już w naszej bazie.')

def unique_username_ignore_case_validator(value):
    if User.objects.filter(username__iexact=value).exists():
        raise ValidationError('Nazwa uzytkownika jest już zajęta.')


class SignUpForm(forms.ModelForm):
    username = forms.CharField(
        error_messages={'required': 'Pole "Nazwa użytkownika" jest wymagane'},
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label="Nazwa użytkownika",
        max_length=30,
        required=True,
        help_text='Nazwa użytkownika może zawierać znaki <strong>[a-z]</strong> i znak "<strong>.</strong>"')

    password = forms.CharField(
        error_messages={'required': 'Pole "Hasło" jest wymagane'},
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Hasło")
    confirm_password = forms.CharField(
        error_messages={'required': 'Pole "Wpisz hasło jeszcze raz" jest wymagane'},
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Wpisz hasło jeszcze raz",
        required=True,
        )
    email = forms.CharField(
        error_messages={'required': 'Pole "email" jest wymagane', 'invalid': 'Podaj prawidłowy adres email'},
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
        required=True,
        max_length=75)
    captcha = ReCaptchaField(attrs={'size': 'normal', 'theme' : 'clean', },
                             error_messages={'required': "Nie uzupełniłeś captcha"})
    class Meta:
        model = User
        exclude = ['last_login', 'date_joined']
        fields = ['username', 'email', 'password', 'confirm_password', ]

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].validators.append(forbidden_usernames_validator)
        self.fields['username'].validators.append(invalid_username_validator)
        self.fields['username'].validators.append(
            unique_username_ignore_case_validator)
        self.fields['email'].validators.append(unique_email_validator)

    def clean(self):
        super(SignUpForm, self).clean()
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password and password != confirm_password:
            self._errors['password'] = self.error_class(
                ['Hasła nie są identyczne'])
        return self.cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class PasswordResetForm2(PasswordResetForm):
    email = forms.EmailField(label=("Email"),
                             max_length=254,
                             error_messages={'required':'pole "Adres email" jest wymagane'},
                             )


class PasswordChangeForm2(PasswordChangeForm):
    old_password = forms.CharField(
        label=_("Old password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autofocus': True}),
        error_messages={'required':'pole "Stare hasło" jest wymagane'})

    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput,
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
        error_messages={'required':'pole "Nowe hasło" jest wymagane'})

    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput,
        error_messages={'required': 'pole "Powtórz hasło" jest wymagane'},
    )

user/views.py
#-*- coding: utf-8 -*-
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetCompleteView, \
    PasswordResetConfirmView, PasswordResetDoneView, \
    PasswordChangeDoneView, PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import JsonResponse
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.generic import CreateView, TemplateView
from rest_framework import viewsets, permissions
from rest_framework.generics import RetrieveAPIView

from common.permissions import IsAdminOrReadOnly
from user.forms import PasswordChangeForm2
from user.models import UserSerializer
from .forms import SignUpForm, MyAuthenticationForm, PasswordResetForm2
from common.mixins import AjaxableResponseMixin, AjaxTemplateMixin, LoginRequiredAjaxMixIn


class LoginView2(SuccessMessageMixin, AjaxTemplateMixin, AjaxableResponseMixin, LoginView):
    template_name = 'user/login.html'
    success_message = "Zostałeś zalogowany"
    form_class = MyAuthenticationForm



class RegisterView(SuccessMessageMixin, AjaxTemplateMixin, AjaxableResponseMixin, CreateView):
    form_class = SignUpForm
    template_name = 'user/register.html'
    success_message = "Zostałeś zarejestrowany"

    def get_success_url(self):
        return reverse('login')


class UserNavView(AjaxTemplateMixin, TemplateView):
    template_name = 'user_nav.html'

class LogoutView2(SuccessMessageMixin, LoginRequiredAjaxMixIn, AjaxTemplateMixin, LogoutView):
    template_name = 'user/logged_out.html'
    success_message = "Zostałeś wylogowany"

    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        #TODO: problem resolved with spaghetti code, find a better way to avoid code repetition in future
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        if self.request.is_ajax():
            logout(request)
            return JsonResponse({"message":"Zostałeś pomyślnie wylogowany"})
        return super().dispatch(request, *args, **kwargs)


class PasswordResetView2(AjaxTemplateMixin, AjaxableResponseMixin, PasswordResetView):
    email_template_name = 'user/password_reset_email.html'
    template_name = 'user/password_reset_form.html'
    success_message = 'Instrukcja pozwalająca ustawić nowe hasło dla podanego adresu email została wysłana. ' \
                      'Niebawem powinna się pojawić na Twoim koncie pocztowym. ' \
                      'W przypadku nieotrzymania wiadomości email upewnij się czy adres wprowadzony jest zgodny ' \
                      'z tym podanym podczas rejestracji i sprawdź zawartość folderu SPAM na swoim koncie.'
    form_class = PasswordResetForm2



class PasswordResetConfirmView2(SuccessMessageMixin, AjaxTemplateMixin, AjaxableResponseMixin, PasswordResetConfirmView):
    template_name = 'user/password_reset_confirm.html'
    success_message = "hasło zostało zmienione"
    post_reset_login = True


class PasswordResetCompleteView2(AjaxTemplateMixin, AjaxableResponseMixin, PasswordResetCompleteView):
    pass


class PasswordResetDoneView2(SuccessMessageMixin, AjaxTemplateMixin, AjaxableResponseMixin, PasswordResetDoneView):
    template_name = 'user/password_reset_done.html'


class PasswordChangeView2(SuccessMessageMixin, LoginRequiredAjaxMixIn, AjaxTemplateMixin, AjaxableResponseMixin,
                          PasswordChangeView):
    template_name = 'user/password_change_form.html'
    form_class = PasswordChangeForm2
    success_message = "hasło zostało pomyślnie zmienione"

class PasswordChangeDoneView2(AjaxTemplateMixin, AjaxableResponseMixin, PasswordChangeDoneView):
    pass

class UserViewSet(viewsets.ModelViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    permission_classes = [permissions.IsAdminUser]

class CheckMail(RetrieveAPIView):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    permission_classes = [permissions.AllowAny]
    lookup_field = 'email'

class CheckUsername(RetrieveAPIView):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    permission_classes = [permissions.AllowAny]
    lookup_field = 'username'

templates/user/logged_out.html
{% extends base %}
{% block main %}
  <ul class="messages">
  {% if messages %}
    {% for message in messages %}
      <li class="alert alert-{{ message.tags }}">{{ message }}</li>
    {% endfor %}{% endif %}
  </ul>
{% endif %}
{% endblock %}

templates/user/login.html
{% extends base %}
{% block main %}
  <ul class="messages">
  {% if messages %}
    {% for message in messages %}
      <li class="alert alert-{{ message.tags }}">{{ message }}</li>
    {% endfor %}{% endif %}
  </ul>
<div class="cover">
    {% if form.non_field_errors %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          {{ error }}
        </div>
      {% endfor %}
    {% endif %}
    <div class="login">
      <h2 class="text-center">Zaloguj się</h2>
      <form id="loginForm" method="post" action="{% url 'login' %}" role="form">
        {% csrf_token %}
        <div class="form-group{% if form.username.errors %} has-error{% endif %}">
          <label for="username">Nazwa użytkownika</label>
          <input required type="text" class="form-control" id="username" name="username">
          {% for error in form.username.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
        <div class="form-group{% if form.password.errors %} has-error{% endif %}">
          <label for="password">Hasło</label>
          <input required type="password" class="form-control" id="password" name="password">
          {% for error in form.password.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
      {{ form.captcha }}
        <div class="form-group text-center">
          <button type="submit" class="btn btn-primary btn-lg">Zaloguj</button>
          <a id="register_button" href="{% url 'register' %}" class="btn btn-primary btn-lg">Zarejestruj</a>
          <a id="reset_password_button" href="{% url 'password_reset' %}" class="btn btn-primary btn-lg">Zapomniałem Hasła</a>
        </div>

      </form>
    </div>
  </div>
{% endblock %}
{% block js %}
    <script type="text/javascript" src="http://www.google.com/recaptcha/api/js/recaptcha_ajax.js"></script>
    <script>
        formsubmit('#loginForm',
            function(data){
                if (data.ok){
                    $("#user_nav").load("{% url 'user_nav' %}");
                    $("#content").load("{% url 'frontpage' %}");
                    $(".messages").append(addmessage(data.message));
                    console.log(data.message);
                }
                },
            function (data) {
            if(data.responseJSON) {
                for(var i in data.responseJSON)
                {
                    $(".messages").append(addmessage(data.responseJSON[i], 'danger'));
                }
            }
            });
        $("#register_button").click(function(event){
            event.preventDefault();
            $("#content").load("{% url 'register' %}");
            });
        $("#reset_password_button").click(function(event){
            event.preventDefault();
            $("#content").load("{% url 'password_reset' %}");
            });
    </script>
{% endblock %}

templates/user/password_change_done.html
{% extends base %}
{% load i18n %}
{% block userlinks %}
    {% url 'django-admindocs-docroot' as docsroot %}
    {% if docsroot %}<a href="{{ docsroot }}">{% trans 'Documentation' %}</a> / {% endif %}
    {% trans 'Change password' %} / <a href="{% url 'frontpage' %}">{% trans 'Log out' %}</a>
{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password change' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}
<p>{% trans 'Your password was changed.' %}</p>
{% endblock %}

templates/user/password_change_form.html
{% extends base %}
{% load i18n static %}
{% block main %}
{% block title%}<h2 class="text-center">{{ title }}</h2>{% endblock %}

{% block content %}
<div id="content-main">
  <ul class="messages">
  {% if messages %}
    {% for message in messages %}
      <li class="alert alert-{{ message.tags }}">{{ message }}</li>
    {% endfor %}{% endif %}
  </ul>
<form id="passwordChangeForm" novalidate action="{% url 'password_change' %}" method="post">{% csrf_token %}
<div>
{% if form.errors %}
    <p class="errornote">
    {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
{% endif %}


<p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>

<div class="form-group">
    {{ form.old_password.errors }}
    <label class="control-label" for="id_old_password">Stare hasło</label>
    <input class="form-control" type="password" name="old_password" autofocus="" required="" id="id_old_password">
</div>

<div class="form-group">
    {{ form.new_password1.errors }}
    <label class="control-label" for="id_new_password1">Nowe hasło</label>
    <input class="form-control" type="password" name="new_password1" required="" id="id_new_password1">
    {% if form.new_password1.help_text %}
    <div class="help">{{ form.new_password1.help_text|safe }}</div>
    {% endif %}
</div>

<div class="form-group">
    {{ form.new_password2.errors }}
    <label class="control-label" for="id_new_password2">Powtórz hasło</label>
    <input class="form-control" type="password" name="new_password2" required="" id="id_new_password2">
    {% if form.new_password2.help_text %}
    <div class="help">{{ form.new_password2.help_text|safe }}</div>
    {% endif %}
</div>

<div class="text-center">
    <button type="submit" class="btn btn-primary btn-lg" >{% trans 'Change my password' %}</button>
</div>

</div>
</form>
</div>

{% endblock %}
{% endblock %}
{% block js %}
    <script>
        formsubmit('#passwordChangeForm',
            function(data){
                if (data.ok){
                    $("#content").load("{% url 'frontpage' %}");
                    $(".messages").append(addmessage(data.message));
                }
                },
            function (data) {
            if(data.responseJSON) {
                console.log(data.responseJSON.values);
                for(var i in data.responseJSON)
                {
                    $(".messages").append(addmessage(data.responseJSON[i], 'danger'));
                }
            }
            });
    </script>
{% endblock %}

templates/user/password_reset_complete.html
{% extends base %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'frontpage' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}

{% block content %}
  <ul class="messages">
  {% if messages %}
    {% for message in messages %}
      <li class="alert alert-{{ message.tags }}">{{ message }}</li>
    {% endfor %}{% endif %}
  </ul>
<p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>

<p><a href="{{ login_url }}">{% trans 'Log in' %}</a></p>

{% endblock %}

templates/user/password_reset_confirm.html
{% extends base %}
{% load i18n static %}

{% block main %}
<h2 class="text-center">{{ title }}</h2>
{% block content %}
  <ul class="messages">
  {% if messages %}
    {% for message in messages %}
      <li class="alert alert-{{ message.tags }}">{{ message }}</li>
    {% endfor %}{% endif %}
  </ul>
{% if validlink %}

<p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

<form id="passwordChangeForm" novalidate role="form" method="post">{% csrf_token %}
    <div class="form-group field-password1">
        {{ form.new_password1.errors }}
        <label for="id_new_password1">{% trans 'New password:' %}</label>
        <input class="form-control" type="password" name="new_password1" required id="id_new_password1">
    </div>
    <div class="form-group field-password2">
        {{ form.new_password2.errors }}
        <label for="id_new_password2">{% trans 'Confirm password:' %}</label>
        <input class="form-control" type="password" name="new_password2" required id="id_new_password2">
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-primary btn-lg">{% trans 'Reset my password' %} </button>
    </div>
</form>

{% else %}
<p class="text-center alert alert-danger">Podany link zmiany hasła jest nieprawidłowy.</p><br>
<div class="text-center">
    <a id="reset_password_button" href="{% url 'password_reset' %}" class="btn btn-primary btn-lg">Zapomniałem Hasła</a>
</div>
{% endif %}
{% endblock %}
{% endblock %}
{% block js %}
    <script>
        formsubmit('#passwordChangeForm',
            function(data){
                if (data.ok){
                    $("#content").load("{% url 'frontpage' %}");
                    $(".messages").append(addmessage(data.message));
                }
                },
            function (data) {
            if(data.responseJSON) {
                console.log(data.responseJSON.values);
                for(var i in data.responseJSON)
                {
                    $(".messages").append(addmessage(data.responseJSON[i], 'danger'));
                }
            }
            });
    </script>
{% endblock %}

templates/user/password_reset_done.html
{% extends base %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}
  <ul class="messages">
  {% if messages %}
    {% for message in messages %}
      <li class="alert alert-{{ message.tags }}">{{ message }}</li>
    {% endfor %}{% endif %}
  </ul>
<p>{% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}</p>

<p>{% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}</p>

{% endblock %}

templates/user/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

templates/user/password_reset_form.html
{% extends base %}
{% load i18n static %}
{% block main %}

    <h2 class="text-center">{{ title }}</h2>
{% block content %}
  <ul class="messages">
  {% if messages %}
    {% for message in messages %}
      <li class="alert alert-{{ message.tags }}">{{ message }}</li>
    {% endfor %}{% endif %}
  </ul>
<p>{% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}</p>

<form id="passwordResetForm" novalidate action="{% url 'password_reset' %}" method="post" role="form">{% csrf_token %}
    <div class="form-group field-email">
        {{ form.email.errors }}
        <label class="control-label" for="id_email">{% trans 'Email address:' %}</label>
        <input class="form-control" type="email" name="email" maxlength="254" required="" id="id_email">
    </div>
    <button type="submit" class="btn btn-primary btn-lg">{% trans 'Reset my password' %} </button>
</form>

{% endblock %}
{% endblock %}
{% block js %}
    <script>
        formsubmit('#passwordResetForm',
            function(data){
                if (data.ok){
                    $("#content").load("{% url 'frontpage' %}");
                    $(".messages").append(addmessage(data.message));
                }
                },
            function (data) {
            if(data.responseJSON) {
                console.log(data.responseJSON.values);
                for(var i in data.responseJSON)
                {
                    $(".messages").append(addmessage(data.responseJSON[i], 'danger'));
                }
            }
            });
    </script>
{% endblock %}

templates/user/register.html
{% extends base %}
{% block main %}
  <ul class="messages">
  {% if messages %}
    {% for message in messages %}
      <li class="alert alert-{{ message.tags }}">{{ message }}</li>
    {% endfor %}{% endif %}
  </ul>
  <div class="signup">
    <h2 class="text-center">Zarejestruj się</h2>
    <form id="registerForm" action="{% url 'register' %}" method="post" role="form">
      {% csrf_token %}
      {% for field in form.visible_fields %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
          <label for="{{ field.label }}">{{ field.label }}</label>
          {{ field }}
          {% if field.help_text %}
            <span class="help-block">{{ field.help_text|safe }}</span>
          {% endif %}
          {% for error in field.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
          <div></div>
      {% endfor %}
      <button type="submit" class="btn btn-primary btn-lg">Utwórz konto</button>
    </form>
  </div>
{% endblock %}
{% block js %}
    <script type="text/javascript" src="http://www.google.com/recaptcha/api/js/recaptcha_ajax.js"></script>
<script>
function ajax_div(text, type){
    if (type){
        type = "danger";
    }
    else {
        type = "success";
    }
    text = "<h3 class='text-center alert-"+type+"'>"+text+"</h3>";
    return text;
}
    formsubmit('#registerForm',
        function(data){
            if (data.ok){
                $("#content").load("{% url 'frontpage' %}");
                $(".messages").append(addmessage(data.message));
            }
        },
        function (data) {
            if(data.responseJSON) {
                for(var i in data.responseJSON)
                {
                    $(".messages").append(addmessage(data.responseJSON[i], 'danger'));
                }
            }
        });
    $("#id_username").focusout(function(){
        if($(this).val().length>0){
        var url="{% url 'check_username' 'desolance' %}".replace('desolance', $(this).val());
        $.ajax({
            context:this,
            url:url,
            success:function () {
                $(this).parent().next().html(ajax_div("Ta nazwa użytkownika jest już zajęta", true));
            },
            error:function (xhr, ajaxOptions, thrownError)
            {
                $(this).parent().next().html(ajax_div("Ta nazwa uzytkownika jest dostępna", false));
            }
        })
    }});
    $("#id_email").focusout(function(){
        if($(this).val().length>0){
        var url="{% url 'check_mail' 'desolance' %}".replace('desolance', $(this).val());
        $.ajax({
            context:this,
            url:url,
            success:function () {
                $(this).parent().next().html(ajax_div("Ten Email jest już zajęty", true));
            },
            error:function (xhr, ajaxOptions, thrownError)
            {
                $(this).parent().next().html(ajax_div("Ten Email jest dostępny", false));
            }

        })

    }});
</script>
{% endblock %}